### ISSUE TITLE
¿Is it works for Asp.NET Core?

### ISSUE THREAD

**Issue by juanluelguerre** [rjperes/Interpose.Core#5]
Hi Ricardo,

First of all, thanks a lot for your Works, it's really good.

I've a doubt about if is it Works for Asp.Net Core. If so, Could you provide an example about how register any proxy inside Startup.cs?

Thanks a lot
Regards
Juanlu

**Comment by rjperes** [comment]
Hi!
Yes, of course it works: it target .NET Standard. I have some examples in the unit tests, maybe I can come up with an ASP.NET Core one.

**Comment by juanluelguerre** [comment]
Could you provide an example about how to use it with IServiceProvider? I didn't found it in the unit tests.
Thanks once again

**Comment by rjperes** [comment]
Please see the sample at https://github.com/rjperes/Interpose.Core/tree/master/Sample.
